import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import {
    AboutComponent,
    AccountBookmarkCourseComponent,
    AccountProfileCoursesComponent,
    AccountProfileDetailsComponent,
    BecomeATeacherComponent,
    BlogDetailsStyleTwoComponent,
    CartComponent,
    CategoriesComponent,
    CheckoutComponent,
    ComingSoonComponent,
    ContactUsComponent,
    CoursesContentDetailComponent,
    CoursesDetailsComponent,
    CoursesListComponent,
    CoursesNewsComponent,
    DownLoadRecoursesComponent,
    FaqComponent,
    GalleryComponent,
    HomeComponent,
    MembershipLevelsComponent,
    NotificationUsersComponent,
    PaymentErrorComponent,
    PrivacyPolicyComponent,
    ProductsDetailsComponent,
    ProfileTeacherComponent,
    PurchaseGuideComponent,
    RegisterErrorComponent,
    RegisterPagesComponent,
    SendEmailAfterRegisterComponent,
    TeacherComponent,
    TermsOfServiceComponent,
    CourseComponent,
    TrainingCourseDetailComponent,
    ProfileComponent,
    CourseListComponent,
    LoginComponent,
    RunCodeComponent,
    VideoLessonComponent,
    PaymentSuccessComponent
} from '@pages';

const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'courses', component: CourseComponent },

    { path: 'training-online/:id', component: TrainingCourseDetailComponent },
    { path: 'profile', component: ProfileComponent },
    { path: 'about', component: AboutComponent },
    { path: 'teacher', component: TeacherComponent },
    { path: 'information-teacher', component: ProfileTeacherComponent },
    { path: 'faq', component: FaqComponent },
    { path: 'coming-soon', component: ComingSoonComponent },
    { path: 'purchase-guide', component: PurchaseGuideComponent },
    { path: 'privacy-policy', component: PrivacyPolicyComponent },
    { path: 'terms-of-service', component: TermsOfServiceComponent },
    // { path: 'courses/:id', component: CoursesListComponent },
    // { path: 'detail-courses/:id', component: CoursesDetailsComponent },
    { path: 'membership-levels', component: MembershipLevelsComponent },
    { path: 'become-teacher', component: BecomeATeacherComponent },
    { path: 'categories', component: CategoriesComponent },
    { path: 'download-document', component: DownLoadRecoursesComponent },
    // { path: 'courses', component: CourseListComponent },
    { path: 'cart', component: CartComponent },
    { path: 'payment/:purchaseCode', component: CheckoutComponent },
    { path: 'details-products', component: ProductsDetailsComponent },
    { path: 'gallery', component: GalleryComponent },
    { path: 'news', component: CoursesNewsComponent },
    { path: 'detail-news', component: BlogDetailsStyleTwoComponent },
    { path: 'contact', component: ContactUsComponent },
    { path: 'detail-content-course/:id', component: CoursesContentDetailComponent },
    { path: 'login', component: LoginComponent },
    { path: 'register', component: RegisterPagesComponent },
    { path: 'my-course', component: AccountProfileCoursesComponent },
    { path: 'my-information', component: AccountProfileDetailsComponent },
    { path: 'training-online', component: CourseComponent },
    { path: 'training-online/:id', component: TrainingCourseDetailComponent },
    { path: 'run-code/:id', component: RunCodeComponent },
    { path: 'video-lesson/:id', component: VideoLessonComponent },

    // Here add new pages component
    { path: 'register-error', component: RegisterErrorComponent },
    { path: 'send-email-register-success', component: SendEmailAfterRegisterComponent },
    { path: 'notification', component: NotificationUsersComponent },
    { path: 'bookmark-course', component: AccountBookmarkCourseComponent },
    { path: 'payment-success', component: PaymentSuccessComponent },
    { path: 'payment-error', component: PaymentErrorComponent }
];

@NgModule({
    imports: [RouterModule.forRoot(routes, {})],
    exports: [RouterModule]
})
export class AppRoutingModule {
}
