using System.Collections.Concurrent;
using System.Text;

namespace CourseMate.Application.Services.FileStorageServices;

public class FakeStorageManager : IFileStorageManager
{
    private readonly ConcurrentDictionary<string, byte[]> _files = new(StringComparer.OrdinalIgnoreCase);

    public Task CreateAsync(IFileEntry fileEntry, Stream stream, CancellationToken cancellationToken = default)
    {
        using MemoryStream memoryStream = new();
        stream.CopyTo(memoryStream);
        _files[fileEntry.FileLocation] = memoryStream.ToArray();
        return Task.CompletedTask;
    }

    public Task<Stream> ReadAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        byte[] content = _files.TryGetValue(fileEntry.FileLocation, out byte[]? value)
            ? value
            : Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager.");
        return Task.FromResult<Stream>(new MemoryStream(content, false));
    }

    public Task<byte[]> ReadBytesAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        byte[] content = _files.TryGetValue(fileEntry.FileLocation, out byte[]? value)
            ? value
            : Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager.");
        return Task.FromResult(content);
    }

    public Task<bool> ExistsAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.FromResult(_files.ContainsKey(fileEntry.FileLocation));
    }

    public Task DeleteAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        _files.TryRemove(fileEntry.FileLocation, out _);
        return Task.CompletedTask;
    }

    public Task ArchiveAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }

    public Task UnArchiveAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
    {
        return Task.CompletedTask;
    }
}