--
-- PostgreSQL database dump
--

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 17.0

-- Started on 2026-04-26 18:38:05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 43230)
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- TOC entry 4061 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- TOC entry 3 (class 3079 OID 43335)
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- TOC entry 4062 (class 0 OID 0)
-- Dependencies: 3
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 225 (class 1259 OID 43708)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- TOC entry 224 (class 1259 OID 43707)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 43663)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- TOC entry 227 (class 1259 OID 43721)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- TOC entry 226 (class 1259 OID 43720)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 43733)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL
);


--
-- TOC entry 229 (class 1259 OID 43745)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL
);


--
-- TOC entry 230 (class 1259 OID 43760)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- TOC entry 219 (class 1259 OID 43670)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" uuid NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- TOC entry 240 (class 1259 OID 43883)
-- Name: CartItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."CartItems" (
    "Id" uuid NOT NULL,
    "CartId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 231 (class 1259 OID 43772)
-- Name: Carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Carts" (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 43677)
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    "Id" uuid NOT NULL,
    "Name" public.citext NOT NULL,
    "Description" public.citext NOT NULL,
    "IsActive" boolean NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 43898)
-- Name: Chapters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Chapters" (
    "Id" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "Title" public.citext NOT NULL,
    "Position" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 234 (class 1259 OID 43806)
-- Name: Courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Courses" (
    "Id" uuid NOT NULL,
    "Title" public.citext NOT NULL,
    "Description" public.citext NOT NULL,
    "Price" numeric NOT NULL,
    "ImageUrl" public.citext NOT NULL,
    "IsPublished" boolean NOT NULL,
    "CategoryId" uuid NOT NULL,
    "InstructorId" uuid NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 242 (class 1259 OID 43910)
-- Name: Enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Enrollments" (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 235 (class 1259 OID 43823)
-- Name: ExerciseDefaultCodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ExerciseDefaultCodes" (
    "Id" uuid NOT NULL,
    "ExerciseId" uuid NOT NULL,
    "Language" character varying(1024) NOT NULL,
    "StarterCode" character varying(32768) NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 236 (class 1259 OID 43835)
-- Name: ExerciseExamples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ExerciseExamples" (
    "Id" uuid NOT NULL,
    "Input" character varying(1024) NOT NULL,
    "Output" character varying(1024) NOT NULL,
    "Explanation" character varying(32768) NOT NULL,
    "ExerciseId" uuid NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 43847)
-- Name: ExerciseTestCases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ExerciseTestCases" (
    "Id" uuid NOT NULL,
    "ExerciseId" uuid NOT NULL,
    "Input" character varying(1024) NOT NULL,
    "ExpectedOutput" character varying(1024) NOT NULL,
    "Description" character varying(1024) NOT NULL,
    "IsHidden" boolean NOT NULL,
    "Order" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 221 (class 1259 OID 43684)
-- Name: Exercises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Exercises" (
    "Id" uuid NOT NULL,
    "Title" public.citext NOT NULL,
    "Description" public.citext NOT NULL,
    "Difficulty" integer NOT NULL,
    "Category" character varying(1024) NOT NULL,
    "CreatorId" uuid NOT NULL,
    "Constraints" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "Hints" jsonb DEFAULT '[]'::jsonb NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 238 (class 1259 OID 43859)
-- Name: FileChunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FileChunks" (
    "Id" uuid NOT NULL,
    "FileEntryId" uuid NOT NULL,
    "ChunkIndex" integer NOT NULL,
    "ChunkPath" character varying(1024) NOT NULL,
    "ChunkSize" bigint NOT NULL,
    "IsUploaded" boolean NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 43693)
-- Name: FileEntries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FileEntries" (
    "Id" uuid NOT NULL,
    "FileName" character varying(1024) NOT NULL,
    "FileSize" double precision NOT NULL,
    "FilePath" character varying(1024) NOT NULL,
    "TempFilePath" character varying(1024) NOT NULL,
    "Status" integer NOT NULL,
    "TotalChunks" integer NOT NULL,
    "UploadedChunks" integer NOT NULL,
    "CompletedAt" timestamp with time zone,
    "FileType" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 43959)
-- Name: FileEntryEmbeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FileEntryEmbeddings" (
    "Id" uuid NOT NULL,
    "FileEntryId" uuid NOT NULL,
    "FileChunkId" uuid NOT NULL,
    "StartIndex" integer NOT NULL,
    "EndIndex" integer NOT NULL,
    "ShortText" character varying(1024) NOT NULL,
    "Embedding" public.vector(768) NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 247 (class 1259 OID 43993)
-- Name: LessonCodings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LessonCodings" (
    "Id" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "ProblemStatement" public.citext NOT NULL,
    "StarterCode" public.citext NOT NULL,
    "ExpectedOutput" public.citext NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 248 (class 1259 OID 44005)
-- Name: LessonMaterials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LessonMaterials" (
    "Id" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "Outline" character varying(32768) NOT NULL,
    "DocumentFileId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 249 (class 1259 OID 44022)
-- Name: LessonQuizzes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LessonQuizzes" (
    "Id" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "Description" public.citext NOT NULL,
    "PassingScore" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 250 (class 1259 OID 44034)
-- Name: LessonReadings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LessonReadings" (
    "Id" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "Content" public.citext NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 251 (class 1259 OID 44046)
-- Name: LessonVideos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."LessonVideos" (
    "Id" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "VideoUrl" public.citext NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 246 (class 1259 OID 43976)
-- Name: Lessons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Lessons" (
    "Id" uuid NOT NULL,
    "ChapterId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "Title" public.citext NOT NULL,
    "LessonType" integer NOT NULL,
    "Position" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 232 (class 1259 OID 43782)
-- Name: Notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Notifications" (
    "Id" uuid NOT NULL,
    "ReceiverId" uuid NOT NULL,
    "Title" public.citext NOT NULL,
    "Message" public.citext NOT NULL,
    "IsRead" boolean NOT NULL,
    "NotificationType" integer NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 243 (class 1259 OID 43925)
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OrderItems" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "Price" numeric NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 43794)
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Status" integer NOT NULL,
    "Description" character varying(32768) NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 43700)
-- Name: OutboxMessages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OutboxMessages" (
    "Id" uuid NOT NULL,
    "EventType" character varying(1024) NOT NULL,
    "TriggeredById" uuid NOT NULL,
    "ObjectId" character varying(1024) NOT NULL,
    "Payload" character varying(32768) NOT NULL,
    "Published" boolean NOT NULL,
    "ActivityId" character varying(1024) NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 43871)
-- Name: PaymentTransactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PaymentTransactions" (
    "Id" uuid NOT NULL,
    "Status" integer NOT NULL,
    "Currency" character varying(1024) NOT NULL,
    "Amount" numeric NOT NULL,
    "Provider" public.citext NOT NULL,
    "FailReason" character varying(1024) NOT NULL,
    "OrderId" uuid NOT NULL,
    "TransactionId" public.citext NOT NULL,
    "RawRequest" character varying(1024) NOT NULL,
    "RawResponse" character varying(1024) NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 244 (class 1259 OID 43942)
-- Name: Reviews; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Reviews" (
    "Id" uuid NOT NULL,
    "CourseId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" public.citext NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 252 (class 1259 OID 44058)
-- Name: UserLessonProgresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserLessonProgresses" (
    "Id" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "LessonId" uuid NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "UserId" uuid,
    "CreationTime" timestamp with time zone NOT NULL,
    "LastModificationTime" timestamp with time zone,
    "IsDeleted" boolean NOT NULL
);


--
-- TOC entry 217 (class 1259 OID 43225)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 4028 (class 0 OID 43708)
-- Dependencies: 225
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4021 (class 0 OID 43663)
-- Dependencies: 218
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4030 (class 0 OID 43721)
-- Dependencies: 227
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4031 (class 0 OID 43733)
-- Dependencies: 228
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4032 (class 0 OID 43745)
-- Dependencies: 229
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4033 (class 0 OID 43760)
-- Dependencies: 230
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4022 (class 0 OID 43670)
-- Dependencies: 219
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4043 (class 0 OID 43883)
-- Dependencies: 240
-- Data for Name: CartItems; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4034 (class 0 OID 43772)
-- Dependencies: 231
-- Data for Name: Carts; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4023 (class 0 OID 43677)
-- Dependencies: 220
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4044 (class 0 OID 43898)
-- Dependencies: 241
-- Data for Name: Chapters; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4037 (class 0 OID 43806)
-- Dependencies: 234
-- Data for Name: Courses; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4045 (class 0 OID 43910)
-- Dependencies: 242
-- Data for Name: Enrollments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4038 (class 0 OID 43823)
-- Dependencies: 235
-- Data for Name: ExerciseDefaultCodes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4039 (class 0 OID 43835)
-- Dependencies: 236
-- Data for Name: ExerciseExamples; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4040 (class 0 OID 43847)
-- Dependencies: 237
-- Data for Name: ExerciseTestCases; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4024 (class 0 OID 43684)
-- Dependencies: 221
-- Data for Name: Exercises; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4041 (class 0 OID 43859)
-- Dependencies: 238
-- Data for Name: FileChunks; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4025 (class 0 OID 43693)
-- Dependencies: 222
-- Data for Name: FileEntries; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4048 (class 0 OID 43959)
-- Dependencies: 245
-- Data for Name: FileEntryEmbeddings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4050 (class 0 OID 43993)
-- Dependencies: 247
-- Data for Name: LessonCodings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4051 (class 0 OID 44005)
-- Dependencies: 248
-- Data for Name: LessonMaterials; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4052 (class 0 OID 44022)
-- Dependencies: 249
-- Data for Name: LessonQuizzes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4053 (class 0 OID 44034)
-- Dependencies: 250
-- Data for Name: LessonReadings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4054 (class 0 OID 44046)
-- Dependencies: 251
-- Data for Name: LessonVideos; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4049 (class 0 OID 43976)
-- Dependencies: 246
-- Data for Name: Lessons; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4035 (class 0 OID 43782)
-- Dependencies: 232
-- Data for Name: Notifications; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4046 (class 0 OID 43925)
-- Dependencies: 243
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4036 (class 0 OID 43794)
-- Dependencies: 233
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4026 (class 0 OID 43700)
-- Dependencies: 223
-- Data for Name: OutboxMessages; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4042 (class 0 OID 43871)
-- Dependencies: 239
-- Data for Name: PaymentTransactions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4047 (class 0 OID 43942)
-- Dependencies: 244
-- Data for Name: Reviews; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4055 (class 0 OID 44058)
-- Dependencies: 252
-- Data for Name: UserLessonProgresses; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- TOC entry 4020 (class 0 OID 43225)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260426113645_Initial', '10.0.5');


--
-- TOC entry 4063 (class 0 OID 0)
-- Dependencies: 224
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 4064 (class 0 OID 0)
-- Dependencies: 226
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 3753 (class 2606 OID 43714)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3737 (class 2606 OID 43669)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3756 (class 2606 OID 43727)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3759 (class 2606 OID 43739)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3762 (class 2606 OID 43749)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3764 (class 2606 OID 43766)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3741 (class 2606 OID 43676)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3796 (class 2606 OID 43887)
-- Name: CartItems PK_CartItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id");


--
-- TOC entry 3767 (class 2606 OID 43776)
-- Name: Carts PK_Carts; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Carts"
    ADD CONSTRAINT "PK_Carts" PRIMARY KEY ("Id");


--
-- TOC entry 3744 (class 2606 OID 43683)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- TOC entry 3799 (class 2606 OID 43904)
-- Name: Chapters PK_Chapters; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chapters"
    ADD CONSTRAINT "PK_Chapters" PRIMARY KEY ("Id");


--
-- TOC entry 3777 (class 2606 OID 43812)
-- Name: Courses PK_Courses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "PK_Courses" PRIMARY KEY ("Id");


--
-- TOC entry 3803 (class 2606 OID 43914)
-- Name: Enrollments PK_Enrollments; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id");


--
-- TOC entry 3780 (class 2606 OID 43829)
-- Name: ExerciseDefaultCodes PK_ExerciseDefaultCodes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseDefaultCodes"
    ADD CONSTRAINT "PK_ExerciseDefaultCodes" PRIMARY KEY ("Id");


--
-- TOC entry 3783 (class 2606 OID 43841)
-- Name: ExerciseExamples PK_ExerciseExamples; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseExamples"
    ADD CONSTRAINT "PK_ExerciseExamples" PRIMARY KEY ("Id");


--
-- TOC entry 3786 (class 2606 OID 43853)
-- Name: ExerciseTestCases PK_ExerciseTestCases; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseTestCases"
    ADD CONSTRAINT "PK_ExerciseTestCases" PRIMARY KEY ("Id");


--
-- TOC entry 3746 (class 2606 OID 43692)
-- Name: Exercises PK_Exercises; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Exercises"
    ADD CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id");


--
-- TOC entry 3789 (class 2606 OID 43865)
-- Name: FileChunks PK_FileChunks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileChunks"
    ADD CONSTRAINT "PK_FileChunks" PRIMARY KEY ("Id");


--
-- TOC entry 3748 (class 2606 OID 43699)
-- Name: FileEntries PK_FileEntries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileEntries"
    ADD CONSTRAINT "PK_FileEntries" PRIMARY KEY ("Id");


--
-- TOC entry 3815 (class 2606 OID 43965)
-- Name: FileEntryEmbeddings PK_FileEntryEmbeddings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileEntryEmbeddings"
    ADD CONSTRAINT "PK_FileEntryEmbeddings" PRIMARY KEY ("Id");


--
-- TOC entry 3822 (class 2606 OID 43999)
-- Name: LessonCodings PK_LessonCodings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonCodings"
    ADD CONSTRAINT "PK_LessonCodings" PRIMARY KEY ("Id");


--
-- TOC entry 3826 (class 2606 OID 44011)
-- Name: LessonMaterials PK_LessonMaterials; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonMaterials"
    ADD CONSTRAINT "PK_LessonMaterials" PRIMARY KEY ("Id");


--
-- TOC entry 3829 (class 2606 OID 44028)
-- Name: LessonQuizzes PK_LessonQuizzes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonQuizzes"
    ADD CONSTRAINT "PK_LessonQuizzes" PRIMARY KEY ("Id");


--
-- TOC entry 3832 (class 2606 OID 44040)
-- Name: LessonReadings PK_LessonReadings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonReadings"
    ADD CONSTRAINT "PK_LessonReadings" PRIMARY KEY ("Id");


--
-- TOC entry 3835 (class 2606 OID 44052)
-- Name: LessonVideos PK_LessonVideos; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonVideos"
    ADD CONSTRAINT "PK_LessonVideos" PRIMARY KEY ("Id");


--
-- TOC entry 3819 (class 2606 OID 43982)
-- Name: Lessons PK_Lessons; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id");


--
-- TOC entry 3770 (class 2606 OID 43788)
-- Name: Notifications PK_Notifications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id");


--
-- TOC entry 3807 (class 2606 OID 43931)
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");


--
-- TOC entry 3773 (class 2606 OID 43800)
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- TOC entry 3750 (class 2606 OID 43706)
-- Name: OutboxMessages PK_OutboxMessages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OutboxMessages"
    ADD CONSTRAINT "PK_OutboxMessages" PRIMARY KEY ("Id");


--
-- TOC entry 3792 (class 2606 OID 43877)
-- Name: PaymentTransactions PK_PaymentTransactions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PaymentTransactions"
    ADD CONSTRAINT "PK_PaymentTransactions" PRIMARY KEY ("Id");


--
-- TOC entry 3811 (class 2606 OID 43948)
-- Name: Reviews PK_Reviews; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id");


--
-- TOC entry 3839 (class 2606 OID 44062)
-- Name: UserLessonProgresses PK_UserLessonProgresses; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserLessonProgresses"
    ADD CONSTRAINT "PK_UserLessonProgresses" PRIMARY KEY ("Id");


--
-- TOC entry 3735 (class 2606 OID 43229)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3739 (class 1259 OID 44078)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3751 (class 1259 OID 44073)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3754 (class 1259 OID 44075)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3757 (class 1259 OID 44076)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3760 (class 1259 OID 44077)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3793 (class 1259 OID 44080)
-- Name: IX_CartItems_CartId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_CartItems_CartId" ON public."CartItems" USING btree ("CartId");


--
-- TOC entry 3794 (class 1259 OID 44081)
-- Name: IX_CartItems_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_CartItems_CourseId" ON public."CartItems" USING btree ("CourseId");


--
-- TOC entry 3765 (class 1259 OID 44082)
-- Name: IX_Carts_StudentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Carts_StudentId" ON public."Carts" USING btree ("StudentId");


--
-- TOC entry 3797 (class 1259 OID 44083)
-- Name: IX_Chapters_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Chapters_CourseId" ON public."Chapters" USING btree ("CourseId");


--
-- TOC entry 3774 (class 1259 OID 44084)
-- Name: IX_Courses_CategoryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Courses_CategoryId" ON public."Courses" USING btree ("CategoryId");


--
-- TOC entry 3775 (class 1259 OID 44085)
-- Name: IX_Courses_InstructorId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Courses_InstructorId" ON public."Courses" USING btree ("InstructorId");


--
-- TOC entry 3800 (class 1259 OID 44086)
-- Name: IX_Enrollments_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Enrollments_CourseId" ON public."Enrollments" USING btree ("CourseId");


--
-- TOC entry 3801 (class 1259 OID 44087)
-- Name: IX_Enrollments_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Enrollments_UserId" ON public."Enrollments" USING btree ("UserId");


--
-- TOC entry 3778 (class 1259 OID 44088)
-- Name: IX_ExerciseDefaultCodes_ExerciseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ExerciseDefaultCodes_ExerciseId" ON public."ExerciseDefaultCodes" USING btree ("ExerciseId");


--
-- TOC entry 3781 (class 1259 OID 44089)
-- Name: IX_ExerciseExamples_ExerciseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ExerciseExamples_ExerciseId" ON public."ExerciseExamples" USING btree ("ExerciseId");


--
-- TOC entry 3784 (class 1259 OID 44090)
-- Name: IX_ExerciseTestCases_ExerciseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ExerciseTestCases_ExerciseId" ON public."ExerciseTestCases" USING btree ("ExerciseId");


--
-- TOC entry 3787 (class 1259 OID 44091)
-- Name: IX_FileChunks_FileEntryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FileChunks_FileEntryId" ON public."FileChunks" USING btree ("FileEntryId");


--
-- TOC entry 3812 (class 1259 OID 44092)
-- Name: IX_FileEntryEmbeddings_FileChunkId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_FileEntryEmbeddings_FileChunkId" ON public."FileEntryEmbeddings" USING btree ("FileChunkId");


--
-- TOC entry 3813 (class 1259 OID 44093)
-- Name: IX_FileEntryEmbeddings_FileEntryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_FileEntryEmbeddings_FileEntryId" ON public."FileEntryEmbeddings" USING btree ("FileEntryId");


--
-- TOC entry 3820 (class 1259 OID 44094)
-- Name: IX_LessonCodings_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_LessonCodings_LessonId" ON public."LessonCodings" USING btree ("LessonId");


--
-- TOC entry 3823 (class 1259 OID 44095)
-- Name: IX_LessonMaterials_DocumentFileId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_LessonMaterials_DocumentFileId" ON public."LessonMaterials" USING btree ("DocumentFileId");


--
-- TOC entry 3824 (class 1259 OID 44096)
-- Name: IX_LessonMaterials_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_LessonMaterials_LessonId" ON public."LessonMaterials" USING btree ("LessonId");


--
-- TOC entry 3827 (class 1259 OID 44097)
-- Name: IX_LessonQuizzes_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_LessonQuizzes_LessonId" ON public."LessonQuizzes" USING btree ("LessonId");


--
-- TOC entry 3830 (class 1259 OID 44098)
-- Name: IX_LessonReadings_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_LessonReadings_LessonId" ON public."LessonReadings" USING btree ("LessonId");


--
-- TOC entry 3833 (class 1259 OID 44101)
-- Name: IX_LessonVideos_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_LessonVideos_LessonId" ON public."LessonVideos" USING btree ("LessonId");


--
-- TOC entry 3816 (class 1259 OID 44099)
-- Name: IX_Lessons_ChapterId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Lessons_ChapterId" ON public."Lessons" USING btree ("ChapterId");


--
-- TOC entry 3817 (class 1259 OID 44100)
-- Name: IX_Lessons_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Lessons_CourseId" ON public."Lessons" USING btree ("CourseId");


--
-- TOC entry 3768 (class 1259 OID 44102)
-- Name: IX_Notifications_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Notifications_UserId" ON public."Notifications" USING btree ("UserId");


--
-- TOC entry 3804 (class 1259 OID 44103)
-- Name: IX_OrderItems_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrderItems_CourseId" ON public."OrderItems" USING btree ("CourseId");


--
-- TOC entry 3805 (class 1259 OID 44104)
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- TOC entry 3771 (class 1259 OID 44105)
-- Name: IX_Orders_StudentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_StudentId" ON public."Orders" USING btree ("StudentId");


--
-- TOC entry 3790 (class 1259 OID 44106)
-- Name: IX_PaymentTransactions_OrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_PaymentTransactions_OrderId" ON public."PaymentTransactions" USING btree ("OrderId");


--
-- TOC entry 3808 (class 1259 OID 44107)
-- Name: IX_Reviews_CourseId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reviews_CourseId" ON public."Reviews" USING btree ("CourseId");


--
-- TOC entry 3809 (class 1259 OID 44108)
-- Name: IX_Reviews_StudentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Reviews_StudentId" ON public."Reviews" USING btree ("StudentId");


--
-- TOC entry 3836 (class 1259 OID 44109)
-- Name: IX_UserLessonProgresses_LessonId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserLessonProgresses_LessonId" ON public."UserLessonProgresses" USING btree ("LessonId");


--
-- TOC entry 3837 (class 1259 OID 44110)
-- Name: IX_UserLessonProgresses_StudentId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserLessonProgresses_StudentId" ON public."UserLessonProgresses" USING btree ("StudentId");


--
-- TOC entry 3738 (class 1259 OID 44074)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3742 (class 1259 OID 44079)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3840 (class 2606 OID 43715)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3841 (class 2606 OID 43728)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3842 (class 2606 OID 43740)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3843 (class 2606 OID 43750)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3844 (class 2606 OID 43755)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3845 (class 2606 OID 43767)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3856 (class 2606 OID 43888)
-- Name: CartItems FK_CartItems_Carts_CartId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES public."Carts"("Id") ON DELETE CASCADE;


--
-- TOC entry 3857 (class 2606 OID 43893)
-- Name: CartItems FK_CartItems_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CartItems"
    ADD CONSTRAINT "FK_CartItems_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3846 (class 2606 OID 43777)
-- Name: Carts FK_Carts_AspNetUsers_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Carts"
    ADD CONSTRAINT "FK_Carts_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3858 (class 2606 OID 43905)
-- Name: Chapters FK_Chapters_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Chapters"
    ADD CONSTRAINT "FK_Chapters_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3849 (class 2606 OID 43813)
-- Name: Courses FK_Courses_AspNetUsers_InstructorId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_AspNetUsers_InstructorId" FOREIGN KEY ("InstructorId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3850 (class 2606 OID 43818)
-- Name: Courses FK_Courses_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Courses"
    ADD CONSTRAINT "FK_Courses_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- TOC entry 3859 (class 2606 OID 43915)
-- Name: Enrollments FK_Enrollments_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3860 (class 2606 OID 43920)
-- Name: Enrollments FK_Enrollments_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Enrollments"
    ADD CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3851 (class 2606 OID 43830)
-- Name: ExerciseDefaultCodes FK_ExerciseDefaultCodes_Exercises_ExerciseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseDefaultCodes"
    ADD CONSTRAINT "FK_ExerciseDefaultCodes_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- TOC entry 3852 (class 2606 OID 43842)
-- Name: ExerciseExamples FK_ExerciseExamples_Exercises_ExerciseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseExamples"
    ADD CONSTRAINT "FK_ExerciseExamples_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- TOC entry 3853 (class 2606 OID 43854)
-- Name: ExerciseTestCases FK_ExerciseTestCases_Exercises_ExerciseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ExerciseTestCases"
    ADD CONSTRAINT "FK_ExerciseTestCases_Exercises_ExerciseId" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE CASCADE;


--
-- TOC entry 3854 (class 2606 OID 43866)
-- Name: FileChunks FK_FileChunks_FileEntries_FileEntryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileChunks"
    ADD CONSTRAINT "FK_FileChunks_FileEntries_FileEntryId" FOREIGN KEY ("FileEntryId") REFERENCES public."FileEntries"("Id") ON DELETE CASCADE;


--
-- TOC entry 3865 (class 2606 OID 43966)
-- Name: FileEntryEmbeddings FK_FileEntryEmbeddings_FileChunks_FileChunkId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileEntryEmbeddings"
    ADD CONSTRAINT "FK_FileEntryEmbeddings_FileChunks_FileChunkId" FOREIGN KEY ("FileChunkId") REFERENCES public."FileChunks"("Id") ON DELETE CASCADE;


--
-- TOC entry 3866 (class 2606 OID 43971)
-- Name: FileEntryEmbeddings FK_FileEntryEmbeddings_FileEntries_FileEntryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FileEntryEmbeddings"
    ADD CONSTRAINT "FK_FileEntryEmbeddings_FileEntries_FileEntryId" FOREIGN KEY ("FileEntryId") REFERENCES public."FileEntries"("Id") ON DELETE CASCADE;


--
-- TOC entry 3869 (class 2606 OID 44000)
-- Name: LessonCodings FK_LessonCodings_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonCodings"
    ADD CONSTRAINT "FK_LessonCodings_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


--
-- TOC entry 3870 (class 2606 OID 44012)
-- Name: LessonMaterials FK_LessonMaterials_FileEntries_DocumentFileId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonMaterials"
    ADD CONSTRAINT "FK_LessonMaterials_FileEntries_DocumentFileId" FOREIGN KEY ("DocumentFileId") REFERENCES public."FileEntries"("Id") ON DELETE CASCADE;


--
-- TOC entry 3871 (class 2606 OID 44017)
-- Name: LessonMaterials FK_LessonMaterials_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonMaterials"
    ADD CONSTRAINT "FK_LessonMaterials_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


--
-- TOC entry 3872 (class 2606 OID 44029)
-- Name: LessonQuizzes FK_LessonQuizzes_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonQuizzes"
    ADD CONSTRAINT "FK_LessonQuizzes_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


--
-- TOC entry 3873 (class 2606 OID 44041)
-- Name: LessonReadings FK_LessonReadings_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonReadings"
    ADD CONSTRAINT "FK_LessonReadings_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


--
-- TOC entry 3874 (class 2606 OID 44053)
-- Name: LessonVideos FK_LessonVideos_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."LessonVideos"
    ADD CONSTRAINT "FK_LessonVideos_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


--
-- TOC entry 3867 (class 2606 OID 43983)
-- Name: Lessons FK_Lessons_Chapters_ChapterId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Chapters_ChapterId" FOREIGN KEY ("ChapterId") REFERENCES public."Chapters"("Id") ON DELETE CASCADE;


--
-- TOC entry 3868 (class 2606 OID 43988)
-- Name: Lessons FK_Lessons_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Lessons"
    ADD CONSTRAINT "FK_Lessons_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3847 (class 2606 OID 43789)
-- Name: Notifications FK_Notifications_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id");


--
-- TOC entry 3861 (class 2606 OID 43932)
-- Name: OrderItems FK_OrderItems_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3862 (class 2606 OID 43937)
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 3848 (class 2606 OID 43801)
-- Name: Orders FK_Orders_AspNetUsers_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3855 (class 2606 OID 43878)
-- Name: PaymentTransactions FK_PaymentTransactions_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PaymentTransactions"
    ADD CONSTRAINT "FK_PaymentTransactions_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- TOC entry 3863 (class 2606 OID 43949)
-- Name: Reviews FK_Reviews_AspNetUsers_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3864 (class 2606 OID 43954)
-- Name: Reviews FK_Reviews_Courses_CourseId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Reviews"
    ADD CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES public."Courses"("Id") ON DELETE CASCADE;


--
-- TOC entry 3875 (class 2606 OID 44063)
-- Name: UserLessonProgresses FK_UserLessonProgresses_AspNetUsers_StudentId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserLessonProgresses"
    ADD CONSTRAINT "FK_UserLessonProgresses_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3876 (class 2606 OID 44068)
-- Name: UserLessonProgresses FK_UserLessonProgresses_Lessons_LessonId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserLessonProgresses"
    ADD CONSTRAINT "FK_UserLessonProgresses_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES public."Lessons"("Id") ON DELETE CASCADE;


-- Completed on 2026-04-26 18:38:05

--
-- PostgreSQL database dump complete
--

